before_script:
- scripts/show_linux_distribution.sh
- GIT_SSL_NO_VERIFY=true git submodule sync
- GIT_SSL_NO_VERIFY=true git submodule update --init
- ln -s /home/radames/software/crave-bundle/deps deps
- NUM_JOBS=$[`nproc`-1]
- if [ "$NUM_JOBS" -lt 1 ]; then NUM_JOBS=1; fi

build_default:
  script: 
  - make -j $NUM_JOBS
  - make test
  tags:
  - linux

build_release:
  script: 
  - ./bootstrap.sh -d deps -m RELEASE --systemc -b cudd -b sword build -DCRAVE_TIMEOUT=60 -DCRAVE_EXAMPLES_TIMEOUT=180
  - make -j $NUM_JOBS
  - make test
  tags:
  - linux
  allow_failure: true

build_boolector:
  script: 
  - ./bootstrap.sh -d deps --systemc -b boolector -b cudd build -DCRAVE_TIMEOUT=60 -DCRAVE_EXAMPLES_TIMEOUT=180
  - cd build
  - make -j $NUM_JOBS
  - ctest --schedule-random -j $NUM_JOBS
  tags:
  - linux
  allow_failure: true

build_cvc4:
  script: 
  - ./bootstrap.sh -d deps --systemc -b cudd -b cvc4 build -DCRAVE_TIMEOUT=60 -DCRAVE_EXAMPLES_TIMEOUT=180
  - cd build
  - make -j $NUM_JOBS
  - ctest --schedule-random -j $NUM_JOBS
  tags:
  - linux
  allow_failure: true

build_yices2:
  script: 
  - ./bootstrap.sh -d deps --systemc -b cudd -b yices2 build -DCRAVE_TIMEOUT=60 -DCRAVE_EXAMPLES_TIMEOUT=180
  - cd build
  - make -j $NUM_JOBS
  - ctest --schedule-random -j $NUM_JOBS
  tags:
  - linux
  allow_failure: true

build_stp:
  script: 
  - ./bootstrap.sh -d deps --systemc -b cudd -b stp build -DCRAVE_TIMEOUT=60 -DCRAVE_EXAMPLES_TIMEOUT=180
  - cd build
  - make -j $NUM_JOBS
  - ctest --schedule-random -j $NUM_JOBS
  tags:
  - linux
  allow_failure: true

build_sword:
  script: 
  - ./bootstrap.sh -d deps --systemc -b cudd -b sword build -DCRAVE_TIMEOUT=60 -DCRAVE_EXAMPLES_TIMEOUT=180
  - cd build
  - make -j $NUM_JOBS
  - ctest --schedule-random -j $NUM_JOBS
  tags:
  - linux
  allow_failure: true

build_sword_no_examples:
  script: 
  - ./bootstrap.sh -d deps --systemc -b cudd -b sword build -DCRAVE_TIMEOUT=60 -DCRAVE_BUILD_EXAMPLES=off
  - cd build
  - make -j $NUM_JOBS
  - ctest --schedule-random -j $NUM_JOBS
  tags:
  - linux
  allow_failure: true

build_sword_no_tests:
  script: 
  - ./bootstrap.sh -d deps --systemc -b cudd -b sword build -DCRAVE_EXAMPLES_TIMEOUT=180 -DCRAVE_ENABLE_TESTS=off
  - cd build
  - make -j $NUM_JOBS
  - ctest --schedule-random -j $NUM_JOBS
  tags:
  - linux
  allow_failure: true

build_z3:
  script: 
  - ./bootstrap.sh -d deps --systemc -b cudd -b z3 build -DCRAVE_TIMEOUT=60 -DCRAVE_EXAMPLES_TIMEOUT=180
  - cd build
  - make -j $NUM_JOBS
  - ctest --schedule-random -j $NUM_JOBS
  tags:
  - linux
  allow_failure: true

