build:
  script: 
  - ./show_linux_distribution.sh
  - git submodule update --init
  - mkdir -p /home/radames/share/deps
  - ln -s /home/radames/share/deps deps
  - make -j
  - make test -j
  tags:
  - linux
  cache:
    paths:
    - deps/